### PR TITLE
integrated DriveNav

### PR DESCRIPTION
**Pull request by makalaaneesh**
Integrated drivenav into the public portal. All complaints registered within a 5km radius of the driver will appear on the issue list and are navigable.

### CODE REVIEW

**Comment by sudheesh001** [comment]
@makalaaneesh Good patch ! :+1:  I am unable to see the list of issues listed down at `/drivenav/issues` but the API does work for `/drivenav/issues/<id>` It looks like I am having the wrong destination on the map , the destination is denoted by `A` being the location of the complaint right ? It looks like its navigating me wierdly. Maybe its just me, I'll look into it closer and merge this. @kranthikiran01 Can you review this too please ?

**Comment by makalaaneesh** [comment]
@sudheesh001 i just rechecked. it's working alright for me! i coded it so that drivenav/issues will only list the complaints within 5km of drivers current location. And in my map, 'A' is your current location and 'B' is the destination!

**Comment by kranthikiran01** [comment]
@sudheesh001 I shall review this by weekend.

On Wed, Jun 24, 2015 at 1:01 AM, Aneesh Makala notifications@github.com
wrote:

> @sudheesh001 https://github.com/sudheesh001 i just rechecked. it's
> working alright for me! i coded it so that drivenav/issues will only list
> the complaints within 5km of drivers current location. And in my map, 'A'
> is your current location and 'B' is the destination!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gearsystems/publicportal/pull/16#issuecomment-114617801
> .

## 

Kranthi Kiran Guduru
Developer,
WSDC, NIT Warangal.

**Comment by sudheesh001** [comment]
Looks okay, the previous design is carried over, we need to push it into the same design as that of the rest of the application but first focus is on getting the application to be running.

**Pull request merged**
