### PR TITLE
Markers db integration

### PR DESCRIPTION
**Pull request by makalaaneesh**
Markers are dropped from Complaint objects. A complaints location is automatically added.

### CODE REVIEW

**Comment by sudheesh001** [comment]
Hi @makalaaneesh 

This code looks good so far, the problem being you uploaded the virtualenv folder and then deleted it, This increases the codebase size because of the commits having content and then being removed, Could you `rebase` the changes so that only one commit is pushed ?

**Comment by sudheesh001** [comment]
Reviewing in progress.

**Comment by makalaaneesh** [comment]
Cool. The markers will reflect in the /dashboard page and a complaints details are automatically  collected when u post one.

**Comment by sudheesh001** [comment]
@makalaaneesh The patch is perfect, but you also committed a `settings.py~` file, This file shouldn't be present, can you remove this file and rebase, then it's good to merge :+1:

**Comment by makalaaneesh** [comment]
@sudheesh001 I removed it and rebased

**Pull request merged**
